## Import Necessary Library

In [1]:
import pandas as pd

## 2. Data Collection

In [4]:
Environment_Data = pd.read_csv("environmental_data.csv")
Environment_Data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

## 3. Data Understanding

In [7]:
Environment_Data.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [8]:
Environment_Data.head(2)

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C

In [9]:
Environment_Data.shape

(158, 10)

In [11]:
Environment_Data.describe(include='all')

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [12]:
Environment_Data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [18]:
Environment_Data

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

In [19]:
Environment_Data.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [26]:
Environment_Data["Weather"].value_counts(dropna = False)

Weather
S      59
C      49
PS     47
NaN     3
Name: count, dtype: int64

## 3. Data Prepartion

#### 3.1 : Data Cleaing

In [27]:
Environment_Data.head(2)

   Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     5    1  2010    67       S
1   36.0    118.0   8.0     5    2  2010    72       C

In [ ]:
Environment_Data.drop(labels = (["Unnamed: 0","Temp C"]),inplace = True,axis= 1) ## Removed Unwanded Columns

In [29]:
Environment_Data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [30]:
Environment_Data.shape

(158, 8)

In [31]:
38/158

0.24050632911392406

In [32]:
## As 25% Data Missing we will drop the Ozone Column

In [33]:
Environment_Data.drop("Ozone",axis = 1,inplace= True)

In [34]:
Environment_Data.head()

   Solar.R  Wind Month  Day  Year  Temp Weather
0    190.0   7.4     5    1  2010    67       S
1    118.0   8.0     5    2  2010    72       C
2    149.0  12.6     5    3  2010    74      PS
3    313.0  11.5     5    4  2010    62       S
4      NaN  14.3     5    5  2010    56       S

In [35]:
Environment_Data.isna().sum()

Solar.R    7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [37]:
Environment_Data[Environment_Data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [41]:
Environment_Data.groupby(by = "Weather")["Solar.R"].mean().round()

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

In [44]:
Environment_Data["Solar.R"] = Environment_Data.groupby(by = "Weather")["Solar.R"].transform(lambda x:x.fillna(x.mean().round()))

In [45]:
Environment_Data.isna().sum()

Solar.R    3
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [47]:
Environment_Data[Environment_Data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87      NaN  12.0     7   27  2010    86     NaN
93      NaN  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [49]:
Environment_Data.dropna(inplace = True)

In [51]:
Environment_Data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [52]:
Environment_Data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [53]:
Environment_Data["Month"].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [55]:
Environment_Data["Month"].replace(to_replace = "May",value = 5,inplace = True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13856\3284450232.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Environment_Data["Month"].replace(to_replace = "May",value = 5,inplace = True)

In [56]:
Environment_Data["Month"].unique()

array(['5', 5, '6', '7', '8', '9'], dtype=object)

In [58]:
Environment_Data["Month"] = Environment_Data["Month"].astype("int")

In [59]:
Environment_Data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

#### Stage 2 :

#### 2. Data Transform :

    If data is Continuous  = Standart scaler,minmax scaler, Robust Scaler
    If data is discrete = Lable Encoder, One Hot Encoder

In [64]:
Environment_Data_C1= Environment_Data.copy()

In [61]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [63]:
Lab_Encode = LabelEncoder()

In [68]:
Environment_Data_C1["Weather"] = Lab_Encode.fit_transform(Environment_Data_C1["Weather"])

In [71]:
Environment_Data_C1.drop(labels = "Wether",inplace = True,axis = 1)

In [72]:
Environment_Data_C1.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather      int64
dtype: object

In [73]:
Environment_Data_C2= Environment_Data.copy()

## One hot decoder can achive in 2 ways

    1. Pandas pd Getdummy
    2. sklear Onehotdecored

## 1. Pandays Ways

In [76]:
Environment_Data_C2.head(2)

   Solar.R  Wind  Month  Day  Year  Temp Weather
0    190.0   7.4      5    1  2010    67       S
1    118.0   8.0      5    2  2010    72       C

In [79]:
Environment_Data_C2 = pd.get_dummies(data = Environment_Data_C2,columns = ["Weather"],dtype = 'int')

In [80]:
Environment_Data_C2

     Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4      5    1  2010    67          0           0          1
1      118.0   8.0      5    2  2010    72          1           0          0
2      149.0  12.6      5    3  2010    74          0           1          0
3      313.0  11.5      5    4  2010    62          0           0          1
4      193.0  14.3      5    5  2010    56          0           0          1
..       ...   ...    ...  ...   ...   ...        ...         ...        ...
153    190.0   7.4      5    1  2010    67          1           0          0
154    193.0   6.9      9   26  2010    70          0           1          0
155    145.0  13.2      9   27  2010    77          0           0          1
156    191.0  14.3      9   28  2010    75          0           0          1
157    131.0   8.0      9   29  2010    76          1           0          0

[155 rows x 9 columns]

### Type 2 : sklearn

In [81]:
from sklearn.preprocessing import OneHotEncoder

In [179]:
Environment_Data_C3 = Environment_Data.copy()

In [169]:
Environment_Data_C3.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [170]:
Environment_Data_C3[["Weather"]]

    Weather
0         S
1         C
2        PS
3         S
4         S
..      ...
153       C
154      PS
155       S
156       S
157       C

[155 rows x 1 columns]

In [171]:
ohe = OneHotEncoder(sparse_output = False,dtype= 'int')

In [172]:
Decoder_DT = ohe.fit_transform(Environment_Data_C3[["Weather"]])

In [167]:
Decoder_DT

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0]])

In [176]:
Environment_Data_C3[["Weather_C","Weather_PS","Weather_S"]] = ohe_out

In [181]:
ohe_out.shape

(155, 3)

In [180]:
Environment_Data_C3.shape

(155, 7)

=============================================== Uploaded in Git HUB =======================================================================