# Chapter 4 : Task 1

Scripting-Based Questions

1.	Write a program to take a name and age from the user and print a greeting message.
2.	Create a list of numbers and print only even numbers using a for loop.
3.	Write a program that handles division by zero using try-except.
4.	Given a string, count how many vowels it has.
5.	Reverse a list without using built-in functions.
6.	Create a dictionary with at least 5 key-value pairs and print them.
7.	Write a Pandas code to read a CSV and print the top 5 rows.
8.	Create a DataFrame from a Python dictionary.
9.	Replace all missing values in a DataFrame with the column’s mean.
10.	Filter rows in a DataFrame where the "Age" column is greater than 30.

###  1.	Write a program to take a name and age from the user and print a greeting message.

In [4]:
try:
    user_name = input("Enter The Name:")
    user_age  = int(input("Enter the Age:"))
    print(f"Hey! Welcom Mr/Mrs . {user_name}, Your age is {user_age}")
except Exception as e:
    print(f"Please validate the Error {e}")
finally:
    print("Thanks! Welcome Back!!")

Enter The Name: Sakthi
Enter the Age: u

Please validate the Error invalid literal for int() with base 10: 'u'
Thanks! Welcome Back!!

### 2.	Create a list of numbers and print only even numbers using a for loop.

In [20]:
## Trying List Comprehension
import random
print(random.choice(range(1,5)))
even_list = [i for i in range(1,100,random.choice(range(1,5))) if i%2 == 0]
print(even_list)

4
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]

### 3.	Write a program that handles division by zero using try-except.

In [26]:
def division():
    try:
        num = int(input("Enter the numarator: "))
        dem = int(input("Enter the denominator: "))
        result = num/dem
        return result
    except Exception as e:
        print(f"Enter the valid numbers other than 0: {e} error")
    finally:
        print("Thanks!!!")

print(division())

Enter the numarator:  e

Enter the valid numbers other than 0: invalid literal for int() with base 10: 'e' error
Thanks!!!
None

###  4.	Given a string, count how many vowels it has.

In [28]:
user_input = input("Enter the string: ")
count:int = 0
for i in user_input.strip().upper():
    if i in "AEIOU":
        count += 1
print(f"Hey! Total Number {count} vowels present in the string' {user_input}'")

Enter the string:  HeY !! I Like Python !!

Hey! Total Number 5 vowels present in the string' HeY !! I Like Python !!'

### 5.	Reverse a list without using built-in functions.

In [32]:
user_list = [1,2,3,4,5,10,6,97]
lst_len = len(user_list)
reverse_list = [0]*lst_len
start = 0
while start < lst_len:
    reverse_list[start] = user_list[lst_len-1]
    reverse_list[lst_len-1] = user_list[start]
    start += 1
    lst_len -= 1

reverse_list

[97, 6, 10, 5, 4, 3, 2, 1]

### 6.	Create a dictionary with at least 5 key-value pairs and print them.

In [35]:
import pandas as pd
dict1 = {'Name' : ['Abi','Sakthi','Magi','kathir','Kavin'],
          'Tamil' : [50,55,56,58,60],
           'English' : [60,65,63,69,67],
             'Maths' : [70,74,76,73,75]
}

df = pd.DataFrame(dict1)
df

     Name  Tamil  English  Maths
0     Abi     50       60     70
1  Sakthi     55       65     74
2    Magi     56       63     76
3  kathir     58       69     73
4   Kavin     60       67     75

In [45]:
df.loc[:,["Name","Tamil"]]

     Name  Tamil
0     Abi     50
1  Sakthi     55
2    Magi     56
3  kathir     58
4   Kavin     60

In [46]:
df.iloc[1]

Name       Sakthi
Tamil          55
English        65
Maths          74
Name: 1, dtype: object

In [48]:
df.iloc[:,[0,1,2]]

     Name  Tamil  English
0     Abi     50       60
1  Sakthi     55       65
2    Magi     56       63
3  kathir     58       69
4   Kavin     60       67

In [51]:
df.iloc[:3,[0,1,2]]

     Name  Tamil  English
0     Abi     50       60
1  Sakthi     55       65
2    Magi     56       63

### 7.	Write a Pandas code to read a CSV and print the top 5 rows.

In [ ]:
emp_data.to_csv

In [60]:
import pandas as pd
emp_data = pd.read_csv("/MyLearning/Python_WS/ProITBridge/Jupyter_Files/Data_File/Pandas_CrassCourse/Employee_data.csv")
emp_data.head().to_csv("/MyLearning/Python_WS/ProITBridge/Jupyter_Files/Data_File/Pandas_CrassCourse/Employee_data_Export.csv")

### 8.	Create a DataFrame from a Python dictionary.

In [61]:
import pandas as pd
dict1 = {'Name' : ['Abi','Sakthi','Magi','kathir','Kavin'],
          'Tamil' : [50,55,56,58,60],
           'English' : [60,65,63,69,67],
             'Maths' : [70,74,76,73,75]
}

df = pd.DataFrame(dict1)
df

     Name  Tamil  English  Maths
0     Abi     50       60     70
1  Sakthi     55       65     74
2    Magi     56       63     76
3  kathir     58       69     73
4   Kavin     60       67     75

### 9.	Replace all missing values in a DataFrame with the column’s mean.

In [64]:
emp_data["Salary"].mean()

np.float64(62500.0)

In [70]:
emp_data["Salary"].fillna(emp_data["Salary"].mean(),inplace = True)

In [71]:
emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech  62500.0  12-11-2020

### 10.	Filter rows in a DataFrame where the "Age" column is greater than 30.

In [74]:
emp_data[emp_data["Age"] > 30]

    Name   Age Department   Salary   Join_Date
1  Nasir  31.0    IT Tech  62500.0  12-11-2020
5  Navin  35.0    Support  72000.0  19-08-2023
6    NaN  40.0         IT  64000.0  10-09-2022
7  Nasir  31.0    IT Tech  62500.0  12-11-2020

In [81]:
emp_data.loc[emp_data["Age"]>30,["Name","Age","Salary"]]

    Name   Age   Salary
1  Nasir  31.0  62500.0
5  Navin  35.0  72000.0
6    NaN  40.0  64000.0
7  Nasir  31.0  62500.0

###### ==================== End ===============================

# Chapter 4 : Task 2

## Task 1
Data Cleaning Challenge on Sales Data.

In [1]:
import pandas as pd

In [2]:
Sales_2017 = pd.read_csv("Data_File/Pandas_CrassCourse/Sales Transactions-2017.csv")
Sales_2018 = pd.read_csv("Data_File/Pandas_CrassCourse/Sales Transactions-2018.csv")
Sales_2019 = pd.read_csv("Data_File/Pandas_CrassCourse/Sales Transactions-2019.csv")
Sales_Edited = pd.read_csv("Data_File/Pandas_CrassCourse/Sales-Transactions-Edited.csv")

In [3]:
Sales_2017.shape

(47290, 9)

In [4]:
Sales_2018.shape

(44740, 9)

In [5]:
Sales_2019.shape

(19176, 9)

In [6]:
Sales_Edited.shape

(95562, 6)

In [7]:
Sales_Edited.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

In [8]:
Sales_Consolidated = pd.concat(objs = [Sales_2017,Sales_2018,Sales_2019])

In [9]:
Sales_Edited.head()

       Date  Voucher               Party            Product  Qty    Rate
0  1/4/2017        1    SOLANKI PLASTICS      DONA-VAI-9100    2  1690.0
1  1/4/2017        1    SOLANKI PLASTICS    LITE FOAM(1200)    6  1620.0
2  1/4/2017        2  SARNESWARA TRADERS  VISHNU CHOTA WINE  500    23.0
3  1/4/2017        2  SARNESWARA TRADERS    LITE FOAM(1200)    6  1620.0
4  1/4/2017        2  SARNESWARA TRADERS      DONA-VAI-9100    5  1690.0

In [10]:
Sales_Consolidated.shape

(111206, 9)

In [11]:
Sales_Consolidated.head()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN

In [12]:
Sales_Consolidated.drop_duplicates(inplace = True)
Sales_Consolidated.shape

(96624, 9)

In [13]:
## Validate all the Null Entries in the given Data and procveed to remove as Key Value is missing
## As this seems Voucher details concerntrate on Vouchers and tring to clean
## 12577 Entries find, So we take backup and Drop in Originatil Data


Sales_Consolidated.isna().sum()

Sales_Consolidated.dropna(subset = "Voucher",inplace = True)

In [14]:
Sales_Consolidated.isna().sum()

Date                 34
Voucher               0
Party                34
Product              34
Qty                   0
Rate                  1
Gross                 1
Disc              92781
Voucher Amount    70814
dtype: int64

In [15]:
### As per the Observation , disc and Voucher Amount Feature are maximum null Entries so, We are droping thos 2 column
Sales_Consolidated.drop(columns = ["Disc","Voucher Amount"],inplace=True)

In [16]:
Sales_Edited.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       1
dtype: int64

In [17]:
Sales_Consolidated.head()

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00"
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00"
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00"

In [18]:
Sales_Consolidated.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate       object
Gross      object
dtype: object

In [19]:
Sales_Consolidated[Sales_Consolidated["Product"].isna()].head()

      Date  Voucher Party Product         Qty        Rate          Gross
4286   NaN  Total     NaN     NaN  725,098.20  892,995.90  10,156,375.86
9440   NaN  Total     NaN     NaN  864,048.00  842,990.34  11,738,640.00
13637  NaN  Total     NaN     NaN  742,449.00  639,799.63   9,994,892.00
17195  NaN  Total     NaN     NaN  569,166.00  684,525.17   9,196,270.50
21653  NaN  Total     NaN     NaN  800,911.60  916,383.98  11,487,277.00

In [20]:
## As product is descrete Data, That can't fill without Clint approval. So we drop the Produuct Null Observation

Sales_Consolidated.dropna(subset = 'Product',inplace= True)

In [21]:
Sales_Consolidated.isnull().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       1
Gross      1
dtype: int64

In [22]:
### As We have Rate and Qty , we are dropping the Gross Amount 

Sales_Consolidated.drop(columns="Gross", inplace= True)

In [23]:
Sales_Consolidated[Sales_Consolidated.duplicated()]

,Date,Voucher,Party,Product,Qty,Rate
8485,24/05/2017,Sal:1867,TP13,Big M.w Spoon,100,15.5
10585,8/6/2017,Sal:2319,TP13,Classic 250ml,100,24
10815,9/6/2017,Sal:2344,TP13,10*10 MORE,25,135
11151,12/6/2017,Sal:2576,TP13,PEPSI 2.0,100,26
11348,13/06/2017,Sal:2435,S.RAMMOHAN-NELLORE,SMART BOWL(3500),1,"1,610.00"
...,...,...,...,...,...,...
13606,14/08/2019,Sal:3446,TP13,APPLE WATER,100,21
14449,23/08/2019,Sal:3680,TP13,APPLE WATER,100,21
14941,27/08/2019,Sal:3823,TP13,Vishnu 250ml,80,29
17952,27/09/2019,Sal:4608,SEKHAR MARKET,14 SILVER PLATES,60,290
19025,9/10/2019,Sal:4904,TP13,Vishnu 250ml,100,29

In [24]:
Sales_Consolidated.drop_duplicates(inplace=True)

In [25]:
Sales_Consolidated.shape

(96357, 6)

In [26]:
Sales_Edited.shape

(95562, 6)

In [27]:
Sales_Consolidated.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       1
dtype: int64

In [28]:
Sales_Consolidated.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [29]:
Sales_Consolidated.head()

       Date Voucher               Party            Product  Qty      Rate
0  1/4/2017   Sal:1    SOLANKI PLASTICS      DONA-VAI-9100    2  1,690.00
1  1/4/2017   Sal:1    SOLANKI PLASTICS    LITE FOAM(1200)    6  1,620.00
2  1/4/2017   Sal:2  SARNESWARA TRADERS  VISHNU CHOTA WINE  500        23
3  1/4/2017   Sal:2  SARNESWARA TRADERS    LITE FOAM(1200)    6  1,620.00
4  1/4/2017   Sal:2  SARNESWARA TRADERS      DONA-VAI-9100    5  1,690.00

In [30]:
Sales_Consolidated

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19167,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140,26
19168,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16

In [30]:
print(Sales_Consolidated["Qty"].unique())

['2' '6' '500' '5' '1' '100' ' ' '150' '10' '200' '3' '20' '50' '30'
 '1,000.00' '25' '2,000.00' '35' '3,000.00' '210' '300' '400' '11' '556'
 '6,000.00' '40' '9' '80' '375' '24' '600' '15' '190' '14' '140' '350'
 '130' '1,800.00' '1,600.00' '800' '939' '230' '700' '70' '27' '72' '250'
 '450' '110' '8' '120' '4' '440' '650' '60' '278' '1,500.00' '240' '312'
 '360' '1,440.00' '270' '25.85' '900' '220' '160' '12' '630' '16' '313'
 '1,400.00' '90' '26' '550' '23' '18' '7' '38' '32' '1,100.00' '125' '750'
 '94' '1,050.00' '2,600.00' '75' '22.6' '480' '4,000.00' '36' '180' '45'
 '5,000.00' '22.3' '26.8' '25.2' '420' '17' '13' '12,000.00' '1,200.00'
 '216' '112' '7,000.00' '84' '105' '330' '840' '62' '26.5' '22.5'
 '4,500.00' '24.5' '3,500.00' '147' '660' '320' '8.52' '63' '1,560.00'
 '23,800.00' '720' '1,350.00' '0.5' '55' '144' '22.4' '2,400.00'
 '24,000.00' '85' '101' '410' '170' '260' '5.5' '460' '614' '5.3' '236'
 '33' '22.45' '18.5' '10,800.00' '980' '560' '29' '61' '310' '280' '44'
 '91' '21' '1,260.00' '1,120.00' '2,500.00' '28' '850' '380' '52' '153'
 '111' '3,400.00' '1,248.00' '95' '48' '2,880.00' '135' '9,600.00'
 '1,080.00' '390' '42' '213' '109' '3,800.00' '5,400.00' '0.6' '4,200.00'
 '37' '41.5' '96' '4,400.00' '19' '385' '22' '1,071.00' '27.1' '108' '142'
 '95.8' '163' '4,600.00' '325' '4.2' '3.2' '31' '447' '23.3' '3,200.00'
 '580' '10.2' '357' '370' '25.8' '272.5' '108.4' '118.7' '640' '23.2'
 '23.4' '1,300.00' '1,980.00' '145' '176' '245' '0.4' '2.84' '5.8' '152'
 '243.5' '100.7' '30.32' '56' '132' '2.5' '114' '432' '104' '405'
 '5,600.00' '106' '51' '73' '530' '290' '130.6' '215' '212.8' '4,800.00'
 '10,200.00' '1,280.00' '10,000.00' '430' '1.95' '192' '2.4' '8,000.00'
 '11.2' '188' '32,000.00' '23.85' '2.3' '324' '2,200.00' '88' '103' '93'
 '740' '930' '3.1' '624' '89.1' '94.9' '108.1' '520' '1,480.00' '760'
 '13.5' '540' '43' '3.5' '4.5' '64' '1,110.00' '28.2' '49' '65'
 '30,000.00' '340' '7.5' '23.5' '265.7' '353.12' '108.2' '50.8'
 '20,000.00' '21.8' '10.05' '23.25' '26,000.00' '10.85' '5.95' '6.6' '175'
 '16,000.00' '15,000.00' '24,900.00' '13.29' '19,400.00' '47' '4.6' '178'
 '67' '109.1' '108.8' '122.5' '5.2' '225' '24.2' '2,700.00' '5.1' '22.1'
 '54' '1,550.00' '18,000.00' '22.2' '24.6' '24.26' '18,400.00' '714'
 '1,650.00' '87' '90.5' '49.9' '53' '1,040.00' '22.25' '10.3' '24.9'
 '74.5' '40.5' '820' '57' '20.5' '3,750.00' '10.5' '22.34' '21.9' '11.1'
 '121' '20.8' '10.1' '20.6' '27.4' '620' '22.7' '17,000.00' '3.16' '20.49'
 '3,300.00' '2,100.00' '237' '268' '43.8' '4.7' '14.2' '21.5' '25.5'
 '21.7' '17.8' '44.5' '834' '10.4' '1,180.00' '68' '25.4' '172' '6,400.00'
 '24.8' '25.6' '123' '6.35' '9,000.00' '31.5' '12.8' '6.31' '2,220.00'
 '156' '5.25' '30.13' '162' '113' '4.9' '71' '2,750.00' '6.7' '133'
 '1,525.00' '19.45' '99' '1,775.00' '3.4' '10.25' '5,250.00' '138' '365'
 '35,000.00' '528' '552' '165' '355' '610' '76' '39' '3,150.00' '1,890.00'
 '219' '1,150.00' '102' '5.02' '5.6' '3.14' '5.07' '2,780.00' '92' '710'
 '2,800.00' '780' '115' '1,320.00' '186' '12.5' '256.5' '340.5' '44.2'
 '2.7' '149' '187' '1,111.00' '880' '34' '265' '27.45' '185' '2,240.00'
 '194' '27.5' '1,250.00' '15.05' '29.9' '32.4' '384' '30.3' '83'
 '1,680.00' '286' '199' '0' '510' '58' '118' '680' '6,600.00' '81' '242'
 '2.8' '1.3' '143' '23.7' '98' '3.8' '429' '41' '4.85' '297' '21.6' '30.9'
 '126' '335' '30.4' '46.8' '53.6' '66' '1.5' '950' '2.2' '30.7' '30.75'
 '11.85' '53.7' '50.3' '30.45' '495' '78' '30.64' '128' '306' '1.1'
 '3,600.00' '73.5' '73.8' '71.5' '71.7' '30.5' '244' '4.8' '6.5' '14.9'
 '825' '46' '10.8' '570' '590' '488' '62.5' '23.16' '31.49' '97' '576'
 '810' '124' '139' '44.8']

In [31]:
Sales_Consolidated = Sales_Consolidated[Sales_Consolidated["Qty"]!=' ']

In [32]:
Sales_Consolidated.head(10)

        Date   Voucher                Party             Product  Qty      Rate
0   1/4/2017     Sal:1     SOLANKI PLASTICS       DONA-VAI-9100    2  1,690.00
1   1/4/2017     Sal:1     SOLANKI PLASTICS     LITE FOAM(1200)    6  1,620.00
2   1/4/2017     Sal:2   SARNESWARA TRADERS   VISHNU CHOTA WINE  500        23
3   1/4/2017     Sal:2   SARNESWARA TRADERS     LITE FOAM(1200)    6  1,620.00
4   1/4/2017     Sal:2   SARNESWARA TRADERS       DONA-VAI-9100    5  1,690.00
5   1/4/2017     Sal:2   SARNESWARA TRADERS  CLASSIC ENJOY(750)    1  1,320.00
6   1/4/2017   Sal:898                 Lock        Vishnu 250ml  100        30
7   1/4/2017   Sal:898                 Lock     BLACK DOG-350ML  100        26
10  1/4/2017  Sal:2497  VAMSI KRISHNA FANCY         Loose Items    1       800
13  1/4/2017  Sal:9263  VAMSI KRISHNA FANCY         Loose Items    1       280

In [33]:
Sales_Edited.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

In [34]:
Sales_Consolidated.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [35]:
Sales_Consolidated.shape

(95226, 6)

In [36]:
Sales_Edited.head()

       Date  Voucher               Party            Product  Qty    Rate
0  1/4/2017        1    SOLANKI PLASTICS      DONA-VAI-9100    2  1690.0
1  1/4/2017        1    SOLANKI PLASTICS    LITE FOAM(1200)    6  1620.0
2  1/4/2017        2  SARNESWARA TRADERS  VISHNU CHOTA WINE  500    23.0
3  1/4/2017        2  SARNESWARA TRADERS    LITE FOAM(1200)    6  1620.0
4  1/4/2017        2  SARNESWARA TRADERS      DONA-VAI-9100    5  1690.0

In [37]:
Sales_Consolidated.head()

       Date Voucher               Party            Product  Qty      Rate
0  1/4/2017   Sal:1    SOLANKI PLASTICS      DONA-VAI-9100    2  1,690.00
1  1/4/2017   Sal:1    SOLANKI PLASTICS    LITE FOAM(1200)    6  1,620.00
2  1/4/2017   Sal:2  SARNESWARA TRADERS  VISHNU CHOTA WINE  500        23
3  1/4/2017   Sal:2  SARNESWARA TRADERS    LITE FOAM(1200)    6  1,620.00
4  1/4/2017   Sal:2  SARNESWARA TRADERS      DONA-VAI-9100    5  1,690.00

In [39]:
Sales_Consolidated

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19167,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140,26
19168,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16

In [40]:
Sales_Consolidated.loc[:,"Voucher"] = Sales_Consolidated["Voucher"].replace("Sal:","",regex= True)

In [41]:
Sales_Consolidated.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [42]:
Sales_Consolidated.head()

       Date Voucher               Party            Product  Qty      Rate
0  1/4/2017       1    SOLANKI PLASTICS      DONA-VAI-9100    2  1,690.00
1  1/4/2017       1    SOLANKI PLASTICS    LITE FOAM(1200)    6  1,620.00
2  1/4/2017       2  SARNESWARA TRADERS  VISHNU CHOTA WINE  500        23
3  1/4/2017       2  SARNESWARA TRADERS    LITE FOAM(1200)    6  1,620.00
4  1/4/2017       2  SARNESWARA TRADERS      DONA-VAI-9100    5  1,690.00

In [43]:
 Sales_Consolidated[Sales_Consolidated["Voucher"] == " "]

  Date Voucher Party Product Qty Rate
3               28/3           0    0
5               25/2           0    0

In [44]:
Sales_Consolidated = Sales_Consolidated[Sales_Consolidated["Voucher"] != " "]

In [46]:
Sales_Consolidated.loc[:,"Voucher"] = Sales_Consolidated["Voucher"].astype(int)

In [47]:
Sales_Consolidated.dtypes

Date       object
Voucher     int64
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [48]:
Sales_Consolidated.loc[:,"Qty"] = Sales_Consolidated["Qty"].str.replace(',','')

In [50]:
Sales_Consolidated.loc[:,"Qty"] = Sales_Consolidated["Qty"].astype(float).astype(int)

In [51]:
Sales_Consolidated.loc[:,"Rate"] = Sales_Consolidated["Rate"].str.replace(',','').astype(float)

In [52]:
Sales_Consolidated.head()

       Date  Voucher               Party            Product  Qty    Rate
0  1/4/2017        1    SOLANKI PLASTICS      DONA-VAI-9100    2  1690.0
1  1/4/2017        1    SOLANKI PLASTICS    LITE FOAM(1200)    6  1620.0
2  1/4/2017        2  SARNESWARA TRADERS  VISHNU CHOTA WINE  500    23.0
3  1/4/2017        2  SARNESWARA TRADERS    LITE FOAM(1200)    6  1620.0
4  1/4/2017        2  SARNESWARA TRADERS      DONA-VAI-9100    5  1690.0

In [53]:
Sales_Consolidated["Date"]

0          1/4/2017
1          1/4/2017
2          1/4/2017
3          1/4/2017
4          1/4/2017
            ...
19167    10/10/2019
19168    10/10/2019
19169    10/10/2019
19170    10/10/2019
19171    10/10/2019
Name: Date, Length: 95224, dtype: object

In [54]:
Sales_Consolidated.loc[:,"Date"] = pd.to_datetime(Sales_Consolidated["Date"],format= '%d/%m/%Y')

In [306]:
Sales_Consolidated

,Date,Voucher,Party,Product,Qty,Rate
0,2017-04-01 00:00:00,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,2017-04-01 00:00:00,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,2017-04-01 00:00:00,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,2017-04-01 00:00:00,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,2017-04-01 00:00:00,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
19167,2019-10-10 00:00:00,4935,K.SRIHARI,16*20(100-W),140,26.0
19168,2019-10-10 00:00:00,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,2019-10-10 00:00:00,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0
19170,2019-10-10 00:00:00,4935,K.SRIHARI,10*12 RK,800,8.5
19171,2019-10-10 00:00:00,4935,K.SRIHARI,13*16 WHITE RK,400,16.0

In [55]:
Sales_Consolidated

,Date,Voucher,Party,Product,Qty,Rate
0,2017-04-01 00:00:00,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,2017-04-01 00:00:00,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,2017-04-01 00:00:00,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,2017-04-01 00:00:00,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,2017-04-01 00:00:00,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
19167,2019-10-10 00:00:00,4935,K.SRIHARI,16*20(100-W),140,26.0
19168,2019-10-10 00:00:00,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,2019-10-10 00:00:00,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0
19170,2019-10-10 00:00:00,4935,K.SRIHARI,10*12 RK,800,8.5
19171,2019-10-10 00:00:00,4935,K.SRIHARI,13*16 WHITE RK,400,16.0

In [56]:
Sales_Consolidated.shape

(95224, 6)

In [57]:
Sales_Consolidated.dtypes

Date       object
Voucher     int64
Party      object
Product    object
Qty         int64
Rate       object
dtype: object

In [59]:
Sales_Consolidated.loc[:,"Rate"] = Sales_Consolidated["Rate"].astype(float)

In [60]:
Sales_Consolidated.describe()

            Voucher           Qty           Rate
count  95224.000000  95224.000000   95223.000000
mean    4469.640248    182.029268     249.897731
std     2810.235591    723.815792    2016.892468
min        1.000000      0.000000       0.010000
25%     2047.750000     10.000000      16.000000
50%     4187.000000     50.000000      28.000000
75%     6854.000000    150.000000     140.000000
max    10042.000000  35000.000000  200000.000000

In [61]:
Sales_Clear_Data = Sales_Consolidated.copy()

In [62]:
Sales_Clear_Data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-04-01 00:00:00,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,2017-04-01 00:00:00,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,2017-04-01 00:00:00,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,2017-04-01 00:00:00,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,2017-04-01 00:00:00,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
19167,2019-10-10 00:00:00,4935,K.SRIHARI,16*20(100-W),140,26.0
19168,2019-10-10 00:00:00,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,2019-10-10 00:00:00,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0
19170,2019-10-10 00:00:00,4935,K.SRIHARI,10*12 RK,800,8.5
19171,2019-10-10 00:00:00,4935,K.SRIHARI,13*16 WHITE RK,400,16.0

### Group By

In [64]:
Sales_Clear_Data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-04-01 00:00:00,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,2017-04-01 00:00:00,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,2017-04-01 00:00:00,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,2017-04-01 00:00:00,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,2017-04-01 00:00:00,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
19167,2019-10-10 00:00:00,4935,K.SRIHARI,16*20(100-W),140,26.0
19168,2019-10-10 00:00:00,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,2019-10-10 00:00:00,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0
19170,2019-10-10 00:00:00,4935,K.SRIHARI,10*12 RK,800,8.5
19171,2019-10-10 00:00:00,4935,K.SRIHARI,13*16 WHITE RK,400,16.0

#### Top 10 Voucher and Qty Purches Based on Party

In [350]:
Sales_Clear_Data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-04-01 00:00:00,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,2017-04-01 00:00:00,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,2017-04-01 00:00:00,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,2017-04-01 00:00:00,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,2017-04-01 00:00:00,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
19167,2019-10-10 00:00:00,4935,K.SRIHARI,16*20(100-W),140,26.0
19168,2019-10-10 00:00:00,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,2019-10-10 00:00:00,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0
19170,2019-10-10 00:00:00,4935,K.SRIHARI,10*12 RK,800,8.5
19171,2019-10-10 00:00:00,4935,K.SRIHARI,13*16 WHITE RK,400,16.0

In [65]:
Sales_Clear_Data.groupby(by= "Party")["Rate"].sum().round().sort_values(ascending = False)

Party
K.SRIHARI              3992785.0
TP13                   2317536.0
HAMPI FOODS            1610015.0
KHAN AND KHAN PLAST     808111.0
SUNDHA PLASTICS         704707.0
                         ...
RSM-PDKR                     8.0
BALAJI PLATICS-SANG          6.0
MADEENA CUT PIECES-          6.0
Lakshmi Plastics-sk          5.0
PARITALA RAMAKRISHN          2.0
Name: Rate, Length: 712, dtype: float64

In [362]:
Sales_Clear_Data.groupby(by= ["Party","Product"])[["Voucher"]].mean()

                                   Voucher
Party           Product
A.BHASKER-VGIRI 14 GREEN           3781.00
                GARUDA 10*12 BLUE  4799.00
                GARUDA 13*16 BLUE  4799.00
                LITE FOAM(1200)    4799.00
                N0-5               4799.00
...                                    ...
YVT-PMR         NO-00              2167.00
                NO-1               2167.00
                NO-2               2167.00
                Tirumala Kirana    9378.00
                Vishnu 250ml       3328.75

[19727 rows x 1 columns]

## Task 2
Merge Function 1 Example

In [66]:
import pandas as pd

In [69]:
Order_dtl = pd.read_excel("Data_File/Pandas_CrassCourse/Meger_Sale_Product_Details.xlsx",sheet_name="Order_Sheet")
Order_dtl

  Order_no     User        Product
0    O-001   Sakthi      Mobile_S1
1    O-002   Karthi      Mobile_iP
2    O-003  Keerthi         Tab_IP
3    O-004     Magi  Laptop_Lenova

In [10]:
!{sys.executable} -m pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---- ----------------------------------- 30.7/250.9 kB ? eta -:--:--
     ---- ----------------------------------- 30.7/250.9 kB ? eta -:--:--
     ---- ----------------------------------- 30.7/250.9 kB ? eta -:--:--
     -------------- --------------------- 102.4/250.9 kB 492.8 kB/s eta 0:00:01
     -------------- --------------------- 102.4/250.9 kB 492.8 kB/s eta 0:00:01
     -------------- --------------------- 102.4/250.9 kB 492.8 kB/s eta 0:00:01
     -------------- --------------------- 102.4/250.9 kB 492.8 kB/s eta 0:00:01
     -------------- --------------------- 102.4/250.9 kB 492.8 kB/s eta 0:00:01
     ------------------------------------ 250.9/250.9 kB 570.3 kB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

In [76]:
Prd_Inventory = pd.read_excel("Data_File/Pandas_CrassCourse/Meger_Sale_Product_Details.xlsx",sheet_name="Inventory_Sheet")
Prd_Inventory

         Product       Prod_Name  Price
0      Mobile_S1  Samsung_Mobile  25000
1      Mobile_iP    Apple Mobile  40000
2         Tab_IP          i-Pad   60000
3  Laptop_Lenova          Laptop  80000

In [79]:
Order_dtl.merge(Prd_Inventory,left_on="Product",right_on="Product",suffixes=('_r','_l'))

  Order_no     User        Product       Prod_Name  Price
0    O-001   Sakthi      Mobile_S1  Samsung_Mobile  25000
1    O-002   Karthi      Mobile_iP    Apple Mobile  40000
2    O-003  Keerthi         Tab_IP          i-Pad   60000
3    O-004     Magi  Laptop_Lenova          Laptop  80000

In [80]:
pd.merge(Order_dtl,Prd_Inventory,how = "left")

  Order_no     User        Product       Prod_Name  Price
0    O-001   Sakthi      Mobile_S1  Samsung_Mobile  25000
1    O-002   Karthi      Mobile_iP    Apple Mobile  40000
2    O-003  Keerthi         Tab_IP          i-Pad   60000
3    O-004     Magi  Laptop_Lenova          Laptop  80000

## Task 3
List Comprehension 2 examples

In [83]:
insurance = pd.read_csv("Data_File/Pandas_CrassCourse/Insurance.csv")
insurance

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

### Group by

In [90]:
insurance.groupby(by = "region")["charges"].mean().round()

region
northeast    13406.0
northwest    12418.0
southeast    14735.0
southwest    12347.0
Name: charges, dtype: float64

### Pivort

In [98]:
insurance[insurance.duplicated()]

Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

In [99]:
insurance.drop_duplicates(inplace=True)

In [103]:
insurance.describe()

               age          bmi     children       charges
count  1337.000000  1337.000000  1337.000000   1337.000000
mean     39.222139    30.663452     1.095737  13279.121487
std      14.044333     6.100468     1.205571  12110.359656
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.290000     0.000000   4746.344000
50%      39.000000    30.400000     1.000000   9386.161300
75%      51.000000    34.700000     2.000000  16657.717450
max      64.000000    53.130000     5.000000  63770.428010

In [112]:
insurance

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [111]:
insurance.pivot_table(values="charges",index="region",columns="sex").round()

sex         female     male
region
northeast  12953.0  13854.0
northwest  12480.0  12421.0
southeast  13500.0  15880.0
southwest  11274.0  13413.0

In [117]:
insurance["Insurance_Eligibility"]=  ["OK" if age > 25 else "Not Ok" for age in insurance["age"]]

In [118]:
insurance

,age,sex,bmi,children,smoker,region,charges,Insurance_Eligibility
0,19,female,27.900,0,yes,southwest,16884.92400,Not Ok
1,18,male,33.770,1,no,southeast,1725.55230,Not Ok
2,28,male,33.000,3,no,southeast,4449.46200,OK
3,33,male,22.705,0,no,northwest,21984.47061,OK
4,32,male,28.880,0,no,northwest,3866.85520,OK
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,OK
1334,18,female,31.920,0,no,northeast,2205.98080,Not Ok
1335,18,female,36.850,0,no,southeast,1629.83350,Not Ok
1336,21,female,25.800,0,no,southwest,2007.94500,Not Ok
1337,61,female,29.070,0,yes,northwest,29141.36030,OK

In [125]:
insurance.groupby(by = "Insurance_Eligibility")[["age","sex"]].count()

                        age   sex
Insurance_Eligibility
Not Ok                  305   305
OK                     1032  1032

In [1]:
insurance

NameError: name 'insurance' is not defined

In [141]:
insurance["Smoker_Eligibility"] = ["Blocked" if i == "yes" else "ok" for i in insurance["smoker"]]

In [142]:
insurance

,age,sex,bmi,children,smoker,region,charges,Insurance_Eligibility,Smoker_Eligibility
0,19,female,27.900,0,yes,southwest,16884.92400,Not Ok,Blocked
1,18,male,33.770,1,no,southeast,1725.55230,Not Ok,ok
2,28,male,33.000,3,no,southeast,4449.46200,OK,ok
3,33,male,22.705,0,no,northwest,21984.47061,OK,ok
4,32,male,28.880,0,no,northwest,3866.85520,OK,ok
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,OK,ok
1334,18,female,31.920,0,no,northeast,2205.98080,Not Ok,ok
1335,18,female,36.850,0,no,southeast,1629.83350,Not Ok,ok
1336,21,female,25.800,0,no,southwest,2007.94500,Not Ok,ok
1337,61,female,29.070,0,yes,northwest,29141.36030,OK,Blocked

## Task 4
Lambda Function 2 examples with Map, Filter, Reduce

In [1]:
import pandas as pd
euro_game = pd.read_csv("Data_File/Pandas_CrassCourse/Euro_2012_stats_TEAM.csv")
euro_game

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [5]:
euro_game.nunique()

Team                          16
Goals                          8
Shots on target               13
Shots off target              13
Shooting Accuracy             15
% Goals-to-shots              14
Total shots (inc. Blocked)    14
Hit Woodwork                   5
Penalty goals                  2
Penalties not scored           2
Headed goals                   4
Passes                        16
Passes completed              16
Passing Accuracy              15
Touches                       16
Crosses                       14
Dribbles                      15
Corners Taken                 13
Tackles                       14
Clearances                    16
Interceptions                 15
Clearances off line            3
Clean Sheets                   4
Blocks                        10
Goals conceded                 7
Saves made                    10
Saves-to-shots ratio          15
Fouls Won                     13
Fouls Conceded                14
Offsides                      12
Yellow Cards                   8
Red Cards                      2
Subs on                        9
Subs off                       9
Players Used                   6
dtype: int64

In [2]:
euro_game.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

In [3]:
euro_game = euro_game[["Team","Goals","Shots on target","Total shots (inc. Blocked)","Fouls Won","Yellow Cards","Red Cards","Players Used"]]

In [4]:
euro_game.sort_values(by = "Goals",ascending= False)

,Team,Goals,Shots on target,Total shots (inc. Blocked),Fouls Won,Yellow Cards,Red Cards,Players Used
13,Spain,12,42,100,102,11,0,18
5,Germany,10,32,80,63,4,0,17
10,Portugal,6,22,82,73,12,0,16
7,Italy,6,34,110,101,16,0,19
14,Sweden,5,17,39,35,7,0,18
12,Russia,5,9,59,34,6,0,16
3,England,5,11,40,43,5,0,16
6,Greece,5,8,32,67,9,1,20
1,Czech Republic,4,13,39,53,7,0,19
0,Croatia,4,13,32,41,9,0,16
2,Denmark,4,10,27,25,4,0,15
4,France,3,22,65,36,6,0,19
8,Netherlands,2,12,60,35,5,0,15
9,Poland,2,15,48,48,7,1,17
15,Ukraine,2,7,38,48,5,0,18
11,Republic of Ireland,1,7,28,43,6,1,17

In [8]:
avg_Rate = euro_game["Goals"].mean().round().astype(int)
avg_Rate

np.int64(5)

In [13]:
euro_game.loc[:,"Team_Strength"] = euro_game["Goals"].map(lambda x: "above Average" if int(x)> avg_Rate else "below_average")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_11656\1472517686.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  euro_game.loc[:,"Team_Strength"] = euro_game["Goals"].map(lambda x: "above Average" if int(x)> avg_Rate else "below_average")

In [14]:
avg_shots = euro_game["Shots on target"].mean().round().astype(int)
avg_shots

np.int64(17)

In [15]:
euro_game.sort_values(by = "Goals",ascending= False)

,Team,Goals,Shots on target,Total shots (inc. Blocked),Fouls Won,Yellow Cards,Red Cards,Players Used,Team_Strength
13,Spain,12,42,100,102,11,0,18,above Average
5,Germany,10,32,80,63,4,0,17,above Average
10,Portugal,6,22,82,73,12,0,16,above Average
7,Italy,6,34,110,101,16,0,19,above Average
14,Sweden,5,17,39,35,7,0,18,below_average
12,Russia,5,9,59,34,6,0,16,below_average
3,England,5,11,40,43,5,0,16,below_average
6,Greece,5,8,32,67,9,1,20,below_average
1,Czech Republic,4,13,39,53,7,0,19,below_average
0,Croatia,4,13,32,41,9,0,16,below_average
2,Denmark,4,10,27,25,4,0,15,below_average
4,France,3,22,65,36,6,0,19,below_average
8,Netherlands,2,12,60,35,5,0,15,below_average
9,Poland,2,15,48,48,7,1,17,below_average
15,Ukraine,2,7,38,48,5,0,18,below_average
11,Republic of Ireland,1,7,28,43,6,1,17,below_average

In [16]:
euro_game.loc[:,"Team_Strngth_Based_On_Shots"] = euro_game["Shots on target"].map(lambda x: "Very Strong Team" if x > avg_shots else "Average Team" )

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_11656\2144575001.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  euro_game.loc[:,"Team_Strngth_Based_On_Shots"] = euro_game["Shots on target"].map(lambda x: "Very Strong Team" if x > avg_shots else "Average Team" )

euro_game

In [17]:
euro_game["Shots on target"].map(lambda x: "Very Strong Team" if x > avg_shots else "Average Team" )

0         Average Team
1         Average Team
2         Average Team
3         Average Team
4     Very Strong Team
5     Very Strong Team
6         Average Team
7     Very Strong Team
8         Average Team
9         Average Team
10    Very Strong Team
11        Average Team
12        Average Team
13    Very Strong Team
14        Average Team
15        Average Team
Name: Shots on target, dtype: object

In [19]:
euro_game.sort_values(by = "Goals")

,Team,Goals,Shots on target,Total shots (inc. Blocked),Fouls Won,Yellow Cards,Red Cards,Players Used,Team_Strength,Team_Strngth_Based_On_Shots
11,Republic of Ireland,1,7,28,43,6,1,17,below_average,Average Team
15,Ukraine,2,7,38,48,5,0,18,below_average,Average Team
8,Netherlands,2,12,60,35,5,0,15,below_average,Average Team
9,Poland,2,15,48,48,7,1,17,below_average,Average Team
4,France,3,22,65,36,6,0,19,below_average,Very Strong Team
0,Croatia,4,13,32,41,9,0,16,below_average,Average Team
2,Denmark,4,10,27,25,4,0,15,below_average,Average Team
1,Czech Republic,4,13,39,53,7,0,19,below_average,Average Team
14,Sweden,5,17,39,35,7,0,18,below_average,Average Team
12,Russia,5,9,59,34,6,0,16,below_average,Average Team
6,Greece,5,8,32,67,9,1,20,below_average,Average Team
3,England,5,11,40,43,5,0,16,below_average,Average Team
10,Portugal,6,22,82,73,12,0,16,above Average,Very Strong Team
7,Italy,6,34,110,101,16,0,19,above Average,Very Strong Team
5,Germany,10,32,80,63,4,0,17,above Average,Very Strong Team
13,Spain,12,42,100,102,11,0,18,above Average,Very Strong Team

#### Filter Function

In [65]:
euro_game.filter(items= ["Team","Goals","Team_Strength"])

euro_game[filter(lambda col: col.startswith('Team') , euro_game.columns)]

                   Team  Team_Strength Team_Strngth_Based_On_Shots
0               Croatia  below_average                Average Team
1        Czech Republic  below_average                Average Team
2               Denmark  below_average                Average Team
3               England  below_average                Average Team
4                France  below_average            Very Strong Team
5               Germany  above Average            Very Strong Team
6                Greece  below_average                Average Team
7                 Italy  above Average            Very Strong Team
8           Netherlands  below_average                Average Team
9                Poland  below_average                Average Team
10             Portugal  above Average            Very Strong Team
11  Republic of Ireland  below_average                Average Team
12               Russia  below_average                Average Team
13                Spain  above Average            Very Strong Team
14               Sweden  below_average                Average Team
15              Ukraine  below_average                Average Team

In [74]:
euro_game[filter(lambda col: col in ["Team","Goals","Team_Strength"] , euro_game.columns)]

                   Team  Goals  Team_Strength
0               Croatia      4  below_average
1        Czech Republic      4  below_average
2               Denmark      4  below_average
3               England      5  below_average
4                France      3  below_average
5               Germany     10  above Average
6                Greece      5  below_average
7                 Italy      6  above Average
8           Netherlands      2  below_average
9                Poland      2  below_average
10             Portugal      6  above Average
11  Republic of Ireland      1  below_average
12               Russia      5  below_average
13                Spain     12  above Average
14               Sweden      5  below_average
15              Ukraine      2  below_average

#### Reduce

In [38]:
from functools import reduce

In [39]:
## Total Goals in the Tournamends 
reduce(lambda x,y:x+y,euro_game["Goals"])

76

In [40]:
### Total Yellow Cards in the tournament
reduce(lambda x,y:x+y,euro_game["Yellow Cards"])

119