#  Python Data Structure Functions

## Task 1

### List

In [7]:
Item_list = []
print(Item_list)

[]

In [2]:
type(Item_list)

list

In [8]:
Item_list.append(10)
Item_list.append(20)
Item_list.append(30)
Item_list.append(40)
Item_list

[10, 20, 30, 40]

In [11]:
Item_list_2 = Item_list.copy()  ## Create New Memory for the Same Object Item, This will not impact the Orijinal Set
Item_list_2

[10, 20, 30, 40]

In [16]:
Item_list3 = Item_list  ## Share the common Memory for both Entity, Any updte one enty will impact Other

In [17]:
Item_list3.insert(2,50)

In [18]:
Item_list3
Item_list

[10, 20, 50, 50, 50, 30, 40]

In [19]:
print(Item_list)

[10, 20, 50, 50, 50, 30, 40]

In [21]:
print(Item_list3)

[10, 20, 50, 50, 50, 30, 40]

In [23]:
Item_list.count(50)

3

In [24]:
Item_list_2.extend(Item_list3)

In [25]:
print(Item_list_2)

[10, 20, 30, 40, 10, 20, 50, 50, 50, 30, 40]

In [29]:
Item_list_2.pop(5)
print(Item_list_2)

[10, 20, 30, 40, 10, 50, 30, 40]

In [30]:
Item_list_2.index(40)

3

In [31]:
Item_list_2.index(40,5)

7

In [32]:
Item_list_2.sort()

In [33]:
print(Item_list_2)

[10, 10, 20, 30, 30, 40, 40, 50]

In [34]:
Item_list_2.sort(reverse=True)

In [35]:
Item_list_2

[50, 40, 40, 30, 30, 20, 10, 10]

In [36]:
Item_list_2.remove(10)

In [37]:
Item_list_2

[50, 40, 40, 30, 30, 20, 10]

In [38]:
Item_list_2.reverse()

In [39]:
Item_list_2

[10, 20, 30, 30, 40, 40, 50]

In [40]:
Item_list4 = Item_list_2.copy()

In [41]:
Item_list4

[10, 20, 30, 30, 40, 40, 50]

In [42]:
Item_list4.clear()

In [43]:
print(Item_list4)

[]

### Tuple

In [45]:
Tu_Item = ()

In [46]:
type(Tu_Item)

tuple

In [48]:
Tu_Item = (10,20,30,40)
Tu_Item

(10, 20, 30, 40)

In [50]:
Tu_Item.count(30)

1

In [51]:
Tu_Item.index(30)

2

### Set

In [52]:
Set_Item = set()

In [53]:
type(Set_Item)

set

In [56]:
Set_Item.add(10)
Set_Item.add(20)
Set_Item.add(30)

In [57]:
Set_Item

{10, 20, 30}

In [59]:
Set_Item2 = {20,30,40}
Set_Item2

{20, 30, 40}

In [61]:
Set_Item3 = Set_Item.copy()
Set_Item3

{10, 20, 30}

In [63]:
Set_Item.difference(Set_Item2)

{10}

In [68]:
Set_Item = Set_Item3.copy()
Set_Item

{10, 20, 30}

In [65]:
Set_Item.difference_update(Set_Item)

In [69]:
Set_Item.intersection(Set_Item2)

{20, 30}

In [72]:
Set_Item3.issubset(Set_Item2)

False

In [73]:
Set_Item.isdisjoint(Set_Item3)

False

### Dictionary

In [74]:
Dict_Item = {}
type(Dict_Item)

dict

In [79]:
Dict_Item = {'Name' : 'Serkar','Tamil':75,'English':60,'Maths': 80}

In [80]:
Dict_Item

{'Name': 'Serkar', 'Tamil': 75, 'English': 60, 'Maths': 80}

In [81]:
Dict_Item1 = Dict_Item.copy()

In [82]:
Dict_Item1

{'Name': 'Serkar', 'Tamil': 75, 'English': 60, 'Maths': 80}

In [83]:
Dict_Item.items()

dict_items([('Name', 'Serkar'), ('Tamil', 75), ('English', 60), ('Maths', 80)])

In [88]:
Dict_Item.keys()

dict_keys(['Name', 'Tamil', 'English', 'Maths'])

In [89]:
Dict_Item.values()

dict_values(['Serkar', 75, 60, 80])

In [101]:
Dict_Item3 = {}
Dict_Item3 = Dict_Item3.fromkeys('Sakthivel',0)
Dict_Item3

{'S': 0, 'a': 0, 'k': 0, 't': 0, 'h': 0, 'i': 0, 'v': 0, 'e': 0, 'l': 0}

In [103]:
Dict_Item3.setdefault('m',0)

0

In [104]:
Dict_Item3

{'S': 0,
 'a': 0,
 'k': 0,
 't': 0,
 'h': 0,
 'i': 0,
 'v': 0,
 'e': 0,
 'l': 0,
 'm': 0}

In [106]:
Dict_Item3.get('k')

0

In [107]:
Dict_Item3.pop('v')

0

In [108]:
Dict_Item3

{'S': 0, 'a': 0, 'k': 0, 't': 0, 'h': 0, 'i': 0, 'e': 0, 'l': 0, 'm': 0}

In [110]:
Dict_Item.popitem()

('English', 60)

In [111]:
Dict_Item

{'Name': 'Serkar', 'Tamil': 75}

###### =========================================== Task1 Completed ===============================================

## Task 2

In [114]:
### Maka Data Fram for Student DataBase
import pandas as pd
dict1 = {'Name' : ['Abi','Sakthi','Magi','kathir','Kavin'],
          'Tamil' : [50,55,56,58,60],
           'English' : [60,65,63,69,67],
             'Maths' : [70,74,76,73,75]
}

df = pd.DataFrame(dict1)

In [115]:
df

     Name  Tamil  English  Maths
0     Abi     50       60     70
1  Sakthi     55       65     74
2    Magi     56       63     76
3  kathir     58       69     73
4   Kavin     60       67     75

In [122]:
#### Make the Customer Invendary for the Store for last 3 Mnth

dict_Store = {'Items' : ['Mobile','Laptop','Key Board','Wireless Mouse'],
              'Apr_Sale_Qty' : [20,10,30,5],
              'May_Sale_Qty' : [70,50,2,0],
               'Jun_Sale_Qty' : [1,8,0,9]}
Item_code = {'Mobile' : 'M001','Laptop' : 'L002','Key Board' : 'K003','Wireless_Mouse' : 'W004'}
df2 = pd.DataFrame(dict_Store,Item_code.values())

In [123]:
df2

               Items  Apr_Sale_Qty  May_Sale_Qty  Jun_Sale_Qty
M001          Mobile            20            70             1
L002          Laptop            10            50             8
K003       Key Board            30             2             0
W004  Wireless Mouse             5             0             9

In [125]:
df2['Items']

M001            Mobile
L002            Laptop
K003         Key Board
W004    Wireless Mouse
Name: Items, dtype: object

In [39]:
####### Create Data From with Timestamp Index 
import pandas as pd
import zoneinfo
from datetime import datetime,timezone

df = pd.DataFrame({
    "Order_Dt":["01/07/2025","01/07/2025","01/07/2025"],
    "sensor_id": ["TL-01", "TL-02", "TL-03"],
    "temperature": [23.5, 24.2, 22.8],
    "humidity": [45, 42, 47]
})

##Sequence : Get Zone detail --> timestamp --> timedeltawith NanoS --> Convert to int64 type
### Insert timestamp
##Get the Time Zone
start_time = zoneinfo.ZoneInfo("Asia/Riyadh")
## Get Current Time from the Zone
base_time = datetime.now(start_time)

## Make the Time Column Unify
df['time'] = [pd.Timestamp(base_time)+pd.Timedelta(nanoseconds=i) for i in range(len(df))]
df['time'] = pd.to_datetime(df['time']).astype('int64')
df.set_index('time',inplace = True)
df

                       Order_Dt sensor_id  temperature  humidity
time
1782931600462644000  01/07/2025     TL-01         23.5        45
1782931600462644001  01/07/2025     TL-02         24.2        42
1782931600462644002  01/07/2025     TL-03         22.8        47