## 1. Import Library

In [1]:
import pandas as pd
from sklearn.

## 2. Data Collection

In [3]:
mv_data = pd.read_csv("Movie.csv")
mv_data

      userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

In [4]:
mv_data.shape

(8992, 3)

In [5]:
mv_data.isna().sum()

userId    0
movie     0
rating    0
dtype: int64

In [8]:
mv_data["userId"].nunique()

4081

In [9]:
mv_data["movie"].nunique()

10

## 3. Data Preparation

### to check the Correlation between the User/ Movies Create the Pivor Table

In [26]:
mv_pivot_Data = pd.pivot_table(data = mv_data,values="rating",index="movie",columns="userId",aggfunc = "mean").fillna(0)
mv_pivot_Data.columns = mv_data["userId"].unique()
mv_pivot_Data

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
movie,,,,,,,,,,,,,,,,,,,,,
Father of the Bride Part II (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,3.5,0.0,0.0,0.0
GoldenEye (1995),0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,2.5,...,2.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0
Grumpier Old Men (1995),0.0,4.0,0.0,0.0,0.0,3.0,3.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
Heat (1995),0.0,0.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,0.0
Jumanji (1995),3.5,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0
Sabrina (1995),0.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.0
Sudden Death (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Tom and Huck (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Toy Story (1995),0.0,0.0,4.0,0.0,0.0,5.0,0.0,4.0,4.0,4.5,...,0.0,4.0,0.0,4.0,0.0,0.0,4.0,4.0,5.0,4.5
Waiting to Exhale (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
mv_pivot_Data.corr().round(3)

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,1.000,-0.111,-0.111,-0.165,1.000,-0.211,-0.167,-0.265,-0.111,-0.159,...,-0.111,-0.111,1.000,0.667,-0.167,-0.111,-0.166,-0.351,-0.111,0.479
6,-0.111,1.000,-0.111,-0.165,-0.111,0.276,0.667,0.564,-0.111,-0.159,...,-0.111,-0.111,-0.111,-0.167,-0.167,-0.111,-0.166,0.351,-0.111,-0.218
8,-0.111,-0.111,1.000,-0.165,-0.111,0.601,-0.167,0.398,1.000,0.862,...,-0.111,1.000,-0.111,0.667,-0.167,-0.111,0.720,0.351,1.000,0.566
10,-0.165,-0.165,-0.165,1.000,-0.165,-0.313,-0.247,0.484,-0.165,0.245,...,0.776,-0.165,-0.165,-0.247,0.987,-0.165,-0.246,0.483,-0.165,-0.322
11,1.000,-0.111,-0.111,-0.165,1.000,-0.211,-0.167,-0.265,-0.111,-0.159,...,-0.111,-0.111,1.000,0.667,-0.167,-0.111,-0.166,-0.351,-0.111,0.479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,-0.111,-0.111,-0.111,-0.165,-0.111,-0.211,-0.167,-0.265,-0.111,-0.159,...,-0.111,-0.111,-0.111,-0.167,-0.167,1.000,0.609,-0.351,-0.111,-0.218
7070,-0.166,-0.166,0.720,-0.246,-0.166,0.332,-0.249,0.132,0.720,0.577,...,-0.166,0.720,-0.166,0.416,-0.249,0.609,1.000,0.035,0.720,0.300
7080,-0.351,0.351,0.351,0.483,-0.351,0.539,0.395,0.813,0.351,0.412,...,0.176,0.351,-0.351,0.000,0.527,-0.351,0.035,1.000,0.351,0.138
7087,-0.111,-0.111,1.000,-0.165,-0.111,0.601,-0.167,0.398,1.000,0.862,...,-0.111,1.000,-0.111,0.667,-0.167,-0.111,0.720,0.351,1.000,0.566
7105,0.479,-0.218,0.566,-0.322,0.479,0.668,0.196,-0.052,0.566,0.409,...,-0.218,0.566,0.479,0.784,-0.327,-0.218,0.300,0.138,0.566,1.000

In [38]:
mv_data[(mv_data["userId"] == 3) | (mv_data["userId"] == 13)]

      userId             movie  rating
0          3  Toy Story (1995)     4.0
6         13  Toy Story (1995)     4.0
2571      13    Jumanji (1995)     3.0
7447      13  GoldenEye (1995)     3.0

In [ ]:
mv_data[(mv_data["userId"] == 3) | (mv_data["userId"] == 11)]

### The above withh show the User based Recommendation

## 2. Another Method to find the recvommendation using Equdian distance

In [23]:
from sklearn.metrics import pairwise_distances

In [28]:
##Pivort the Data As per Movies 

EQ_mv_pivot_Data = pd.pivot_table(data = mv_data,values="rating",index="userId",columns="movie").fillna(0)
EQ_mv_pivot_Data.columns = mv_data["movie"].unique()
EQ_mv_pivot_Data

,Toy Story (1995),Jumanji (1995),Grumpier Old Men (1995),Waiting to Exhale (1995),Father of the Bride Part II (1995),Heat (1995),Sabrina (1995),Tom and Huck (1995),Sudden Death (1995),GoldenEye (1995)
userId,,,,,,,,,,
1,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
4,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
7115,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7116,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
7117,0.0,3.0,4.0,5.0,0.0,3.0,1.0,0.0,4.0,0.0
7119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
7120,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,4.5,0.0

In [33]:
mv_Equidian_Corr = pd.DataFrame(pairwise_distances(X = EQ_mv_pivot_Data,metric='euclidean'),columns=mv_data["userId"].unique(),index=mv_data["userId"].unique())
mv_Equidian_Corr

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,0.000000,5.315073,5.315073,6.103278,0.500000,8.440972,5.500000,8.845903,5.315073,6.224950,...,4.031129,5.315073,1.500000,4.031129,5.500000,5.315073,6.363961,9.394147,6.103278,6.041523
6,5.315073,0.000000,5.656854,6.403124,5.000000,7.141428,3.162278,6.480741,5.656854,6.519202,...,4.472136,5.656854,4.472136,6.928203,5.830952,5.656854,6.652067,7.745967,6.403124,8.261356
8,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,...,4.472136,0.000000,4.472136,4.000000,5.830952,5.656854,3.500000,7.745967,1.000000,5.678908
10,6.103278,6.403124,6.403124,0.000000,5.830952,9.165151,6.557439,6.403124,6.403124,5.612486,...,3.605551,6.403124,5.385165,7.549834,1.000000,6.403124,7.297260,6.855655,7.071068,8.789198
11,0.500000,5.000000,5.000000,5.830952,0.000000,8.246211,5.196152,8.660254,5.000000,5.958188,...,3.605551,5.000000,1.000000,4.123106,5.196152,5.000000,6.103278,9.219544,5.830952,6.103278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,5.315073,5.656854,5.656854,6.403124,5.000000,8.660254,5.830952,9.055385,5.656854,6.519202,...,4.472136,5.656854,4.472136,6.928203,5.830952,0.000000,4.031129,9.591663,6.403124,8.261356
7070,6.363961,6.652067,3.500000,7.297260,6.103278,6.873864,6.800735,7.889867,3.500000,4.330127,...,5.678908,3.500000,5.678908,5.315073,6.800735,4.031129,0.000000,8.500000,3.640055,6.670832
7080,9.394147,7.745967,7.745967,6.855655,9.219544,6.403124,7.211103,4.000000,7.745967,7.176350,...,8.246211,7.745967,8.944272,8.717798,6.782330,9.591663,8.500000,0.000000,7.810250,8.261356
7087,6.103278,6.403124,1.000000,7.071068,5.830952,5.830952,6.557439,7.141428,1.000000,2.549510,...,5.385165,1.000000,5.385165,4.123106,6.557439,6.403124,3.640055,7.810250,0.000000,5.678908
7105,6.041523,8.261356,5.678908,8.789198,6.103278,5.123475,6.800735,9.069179,5.678908,6.184658,...,7.500000,5.678908,6.344289,4.031129,8.381527,8.261356,6.670832,8.261356,5.678908,0.000000

### 2.1 Cosine metric

In [35]:
mv_cosine_Corr = pd.DataFrame(1-pairwise_distances(X = EQ_mv_pivot_Data,metric='cosine'),columns=mv_data["userId"].unique(),index=mv_data["userId"].unique())
mv_cosine_Corr

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.553372
6,0.000000,1.000000,0.000000,0.000000,0.000000,0.390567,0.707107,0.615457,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.458831,0.000000,0.000000
8,0.000000,0.000000,1.000000,0.000000,0.000000,0.650945,0.000000,0.492366,1.000000,0.874157,...,0.000000,1.000000,0.000000,0.707107,0.000000,0.000000,0.752577,0.458831,1.000000,0.622543
10,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.615457,0.000000,0.388514,...,0.800000,0.000000,0.000000,0.000000,0.989949,0.000000,0.000000,0.619422,0.000000,0.000000
11,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.553372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.658505,0.000000,0.000000,0.000000
7070,0.000000,0.000000,0.752577,0.000000,0.000000,0.489886,0.000000,0.370543,0.752577,0.657870,...,0.000000,0.752577,0.000000,0.532152,0.000000,0.658505,1.000000,0.345306,0.752577,0.468511
7080,0.000000,0.458831,0.458831,0.619422,0.000000,0.701884,0.567775,0.889532,0.458831,0.568212,...,0.344124,0.458831,0.000000,0.324443,0.648886,0.000000,0.345306,1.000000,0.458831,0.476071
7087,0.000000,0.000000,1.000000,0.000000,0.000000,0.650945,0.000000,0.492366,1.000000,0.874157,...,0.000000,1.000000,0.000000,0.707107,0.000000,0.000000,0.752577,0.458831,1.000000,0.622543
7105,0.553372,0.000000,0.622543,0.000000,0.553372,0.765455,0.391293,0.306519,0.622543,0.544201,...,0.000000,0.622543,0.553372,0.831497,0.000000,0.000000,0.468511,0.476071,0.622543,1.000000

In [37]:
## Observer 1st 20 Observation

mv_Equidian_Corr.iloc[:20,:20]

,3,6,8,10,11,12,13,14,16,19,22,23,24,31,34,39,47,53,54,58
3,0.000000,5.315073,5.315073,6.103278,0.500000,8.440972,5.500000,8.845903,5.315073,6.224950,7.697402,5.024938,6.689544,4.031129,5.500000,5.315073,10.161201,5.315073,6.800735,5.315073
6,5.315073,0.000000,5.656854,6.403124,5.000000,7.141428,3.162278,6.480741,5.656854,6.519202,6.244998,7.071068,6.964194,4.472136,5.830952,5.656854,8.660254,5.656854,7.071068,5.656854
8,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,5.567764,4.242641,3.535534,4.472136,3.162278,5.656854,8.185353,5.656854,5.099020,0.000000
10,6.103278,6.403124,6.403124,0.000000,5.830952,9.165151,6.557439,6.403124,6.403124,5.612486,7.348469,5.916080,7.582875,3.605551,5.000000,4.123106,9.273618,4.123106,5.385165,6.403124
11,0.500000,5.000000,5.000000,5.830952,0.000000,8.246211,5.196152,8.660254,5.000000,5.958188,7.483315,5.000000,6.442049,3.605551,5.196152,5.000000,10.000000,5.000000,6.557439,5.000000
12,8.440972,7.141428,5.916080,9.165151,8.246211,0.000000,5.385165,7.416198,5.916080,6.363961,4.242641,7.280110,3.391165,7.937254,6.855655,8.660254,5.099020,8.660254,7.937254,5.916080
13,5.500000,3.162278,5.830952,6.557439,5.196152,5.385165,0.000000,7.348469,5.830952,6.670832,5.385165,7.211103,5.431390,4.690416,6.000000,5.830952,7.416198,5.830952,7.211103,5.830952
14,8.845903,6.480741,7.071068,6.403124,8.660254,7.416198,7.348469,0.000000,7.071068,6.041523,5.744563,6.633250,7.905694,7.348469,6.480741,7.615773,6.855655,7.615773,6.782330,7.071068
16,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,5.567764,4.242641,3.535534,4.472136,3.162278,5.656854,8.185353,5.656854,5.099020,0.000000
19,6.224950,6.519202,2.549510,5.612486,5.958188,6.363961,6.670832,6.041523,2.549510,0.000000,6.123724,3.082207,4.301163,4.527693,4.183300,6.519202,8.514693,6.519202,5.787918,2.549510
22,7.697402,6.244998,5.567764,7.348469,7.483315,4.242641,5.385165,5.744563,5.567764,6.123724,0.000000,7.000000,4.743416,7.141428,4.795832,6.244998,3.741657,6.244998,5.196152,5.567764
23,5.024938,7.071068,4.242641,5.916080,5.000000,7.280110,7.211103,6.633250,4.242641,3.082207,7.000000,0.000000,5.522681,5.099020,5.291503,7.071068,9.219544,7.071068,6.633250,4.242641
24,6.689544,6.964194,3.535534,7.582875,6.442049,3.391165,5.431390,7.905694,3.535534,4.301163,4.743416,5.522681,0.000000,6.041523,4.847680,6.964194,6.595453,6.964194,6.284903,3.535534
31,4.031129,4.472136,4.472136,3.605551,3.605551,7.937254,4.690416,7.348469,4.472136,4.527693,7.141428,5.099020,6.041523,0.000000,4.690416,4.472136,9.746794,4.472136,6.164414,4.472136
34,5.500000,5.830952,3.162278,5.000000,5.196152,6.855655,6.000000,6.480741,3.162278,4.183300,4.795832,5.291503,4.847680,4.690416,0.000000,3.162278,7.000000,3.162278,2.000000,3.162278
39,5.315073,5.656854,5.656854,4.123106,5.000000,8.660254,5.830952,7.615773,5.656854,6.519202,6.244998,7.071068,6.964194,4.472136,3.162278,0.000000,8.185353,0.000000,3.162278,5.656854
47,10.161201,8.660254,8.185353,9.273618,10.000000,5.099020,7.416198,6.855655,8.185353,8.514693,3.741657,9.219544,6.595453,9.746794,7.000000,8.185353,0.000000,8.185353,6.708204,8.185353
53,5.315073,5.656854,5.656854,4.123106,5.000000,8.660254,5.830952,7.615773,5.656854,6.519202,6.244998,7.071068,6.964194,4.472136,3.162278,0.000000,8.185353,0.000000,3.162278,5.656854
54,6.800735,7.071068,5.099020,5.385165,6.557439,7.937254,7.211103,6.782330,5.099020,5.787918,5.196152,6.633250,6.284903,6.164414,2.000000,3.162278,6.708204,3.162278,0.000000,5.099020
58,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,5.567764,4.242641,3.535534,4.472136,3.162278,5.656854,8.185353,5.656854,5.099020,0.000000

In [41]:
mv_data[(mv_data["userId"] == 39) | (mv_data["userId"] == 53)]

      userId             movie  rating
15        39  Toy Story (1995)     5.0
17        53  Toy Story (1995)     4.0
5214      39       Heat (1995)     5.0

In [44]:
mv_data[(mv_data["userId"] == 3) | (mv_data["userId"] == 11)]

      userId             movie  rating
0          3  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
7446      11  GoldenEye (1995)     2.5