## 1. Import Necessary Library

In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

## 2. Load Data

In [2]:
dia_data = pd.read_csv("diabetes.csv")

In [3]:
dia_data

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0              6      148             72             35        0  33.6                     0.627   50        1
1              1       85             66             29        0  26.6                     0.351   31        0
2              8      183             64              0        0  23.3                     0.672   32        1
3              1       89             66             23       94  28.1                     0.167   21        0
4              0      137             40             35      168  43.1                     2.288   33        1
..           ...      ...            ...            ...      ...   ...                       ...  ...      ...
763           10      101             76             48      180  32.9                     0.171   63        0
764            2      122             70             27        0  36.8                     0.340   27        0
765            5      121             72             23      112  26.2                     0.245   30        0
766            1      126             60              0        0  30.1                     0.349   47        1
767            1       93             70             31        0  30.4                     0.315   23        0

[768 rows x 9 columns]

In [4]:
X = dia_data.drop("Outcome",axis = 1)
y = dia_data.Outcome

In [26]:
X_train,X_test,y_train,y_Test = train_test_split(X,y,test_size=0.2,shuffle=True,random_state=12,stratify=y)

In [27]:
X_train.shape,X_test.shape,y_train.shape,y_Test.shape

((614, 8), (154, 8), (614,), (154,))

## 3, Data Preprocessing

In [7]:
scaler = StandardScaler()

In [8]:
X_train = scaler.fit_transform(X_train)

In [9]:
X_test = scaler.transform(X_test)

### HYPERPARAMETER TUNING

#### List the Hyperparamaters we used so far....
1. Learning Rate
2. Epochs
3. Batches
4. Activation Functions
5. Optimizers
6. Loss Functions
7. Kernel Initializers

### ====================================================================================================================

In [16]:
pip install scikeras

Collecting scikeras
  Using cached scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: keras>=3.2.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from scikeras) (3.12.4)
Requirement already satisfied: scikit-learn>=1.4.2 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from scikeras) (1.7.2)
Requirement already satisfied: absl-py in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (2.5.0)
Requirement already satisfied: numpy in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (2.2.6)
Requirement already satisfied: rich in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (15.0.0)
Requirement already satisfied: namex in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (3.14.0)
Requirement already satisfied: optree in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (0.19.1)
Requirement already satisfied: ml-dtypes in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (0.5.4)
Requirement already satisfied: packaging in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (26.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from optree->keras>=3.2.0->scikeras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from rich->keras>=3.2.0->scikeras) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from rich->keras>=3.2.0->scikeras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Using cached scikeras-0.13.0-py3-none-any.whl (26 kB)
Installing collected packages: scikeras
Successfully installed scikeras-0.13.0
Note: you may need to restart the kernel to use updated packages.

### Steps for the Hyperparameter Tuning

    Wrapper Class
    |
    Combine the Module Architecture
    |
    Pass the GridSearchCV to find the BestParameter
    |
    Retrain the Module with Optimal Parameter
    |
    Get the Intelligent File(.h5)"

In [18]:
### Import the required Libarary
import numpy as np
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV,KFold

In [35]:
def create_module(learning_Rate = 0.01,dropout_rate = 0.0,act_func = 'relu',init = 'glorot_uniform',n2 = 4,n1 = 8):
    model = Sequential()
    model.add(Dense(n1,kernel_initializer = init,activation = act_func,input_shape=(8,)))
    model.add(Dropout(dropout_rate))
    model.add(Dense(n2,kernel_initializer= init,activation=act_func))
    model.add(Dropout(dropout_rate))
    model.add(Dense(1,activation='sigmoid'))
    
    Optimizer = keras.optimizers.Adam(learning_Rate)
    model.compile(Optimizer,loss = 'binary_crossentropy',metrics = ['accuracy'])
    return model

In [36]:
model = KerasClassifier(model=create_module,verbose = 1)

In [37]:
param_grid = {'model__learning_Rate': [0.001, 0.01],
              #if its model_lr = Just variable naming, but here it is model__learning_rate -> Navigate inside object
              'model__dropout_rate': [0.0, 0.2],
              'model__act_func': ['relu', 'tanh'],
              'model__init': ['glorot_uniform', 'he_uniform'],
              'model__n2':[4, 8],
              'model__n1':[8, 16],
              'batch_size': [10, 20],
              'epochs': [10, 50]
            }

In [38]:
K_fole_param = KFold(n_splits=3, shuffle=True, random_state=12)
grid = GridSearchCV(estimator = model,param_grid = param_grid, cv=K_fole_param,verbose=10,n_jobs = -1)

In [39]:
grid_result = grid.fit(X_train,y_train)

Fitting 3 folds for each of 256 candidates, totalling 768 fits

C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\joblib\externals\loky\process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5733 - loss: 3.8771
Epoch 2/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6254 - loss: 1.5024
Epoch 3/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6678 - loss: 0.8043
Epoch 4/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6173 - loss: 1.2002
Epoch 5/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6173 - loss: 1.2485
Epoch 6/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6450 - loss: 0.8587
Epoch 7/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6580 - loss: 0.7729
Epoch 8/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6938 - loss: 0.6831
Epoch 9/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6564 - loss: 0.7410
Epoch 10/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6872
Epoch 11/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6433 - loss: 0.8002
Epoch 12/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6824 - loss: 0.7070
Epoch 13/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7150 - loss: 0.6497
Epoch 14/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6743 - loss: 0.6414
Epoch 15/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6938 - loss: 0.6222
Epoch 16/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6808 - loss: 0.6281
Epoch 17/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6824 - loss: 0.6280
Epoch 18/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7150 - loss: 0.5695
Epoch 19/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7036 - loss: 0.6019
Epoch 20/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6808 - loss: 0.6183
Epoch 21/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7166 - loss: 0.5682
Epoch 22/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6743 - loss: 0.6216
Epoch 23/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7150 - loss: 0.5717
Epoch 24/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7068 - loss: 0.5643
Epoch 25/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7248 - loss: 0.5556
Epoch 26/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7313 - loss: 0.5678
Epoch 27/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7068 - loss: 0.5691
Epoch 28/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7394 - loss: 0.5525
Epoch 29/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7280 - loss: 0.5388
Epoch 30/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7215 - loss: 0.5542
Epoch 31/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7443 - loss: 0.5482
Epoch 32/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7264 - loss: 0.5547
Epoch 33/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7362 - loss: 0.5453
Epoch 34/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7199 - loss: 0.5477
Epoch 35/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7378 - loss: 0.5421
Epoch 36/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7313 - loss: 0.5490
Epoch 37/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7590 - loss: 0.5183
Epoch 38/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7313 - loss: 0.5359
Epoch 39/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7459 - loss: 0.5377
Epoch 40/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7378 - loss: 0.5420
Epoch 41/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7264 - loss: 0.5399
Epoch 42/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7378 - loss: 0.5252
Epoch 43/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7427 - loss: 0.5283
Epoch 44/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7524 - loss: 0.5273
Epoch 45/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7166 - loss: 0.5581
Epoch 46/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7492 - loss: 0.5356
Epoch 47/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7476 - loss: 0.5297
Epoch 48/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7345 - loss: 0.5239
Epoch 49/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7378 - loss: 0.5474
Epoch 50/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7296 - loss: 0.5357

In [41]:
print("Best of %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best of 0.716563 using {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}

In [45]:
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']

for mean, std, param in zip(means, stds, params):
    print("%f (%f) with: %s" % (mean, std, param))

0.613869 (0.059753) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 4}
0.597657 (0.029209) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 8}
0.560386 (0.103114) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 4}
0.618827 (0.028564) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 8}
0.667687 (0.034728) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 4}
0.656281 (0.034663) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}
0.677451 (0.043695) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 4}
0.680783 (0.013946) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 8}
0.651443 (0.010794) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 4}
0.592866 (0.047912) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 8}
0.574805 (0.068757) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 4}
0.628686 (0.046783) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 8}
0.659605 (0.002779) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 4}
0.667799 (0.021525) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}
0.641663 (0.016787) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 4}
0.644931 (0.016536) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 8}
0.659613 (0.004264) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 4}
0.526088 (0.041820) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 8}
0.628663 (0.031875) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 4}
0.597768 (0.046792) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 8}
0.648183 (0.011369) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 4}
0.656329 (0.010021) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 4}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 8}
0.630297 (0.039856) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 4}
0.557054 (0.049047) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 8}
0.631923 (0.025891) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 4}
0.643305 (0.017714) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 8}
0.654687 (0.016885) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 4}
0.664443 (0.022778) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 4}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 8}
0.653053 (0.018212) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 4}
0.651395 (0.031809) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 8}
0.638403 (0.018925) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 4}
0.641687 (0.024102) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 8}
0.646533 (0.020522) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 4}
0.648183 (0.011369) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}
0.644907 (0.019683) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 4}
0.644859 (0.040039) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 8}
0.613877 (0.056400) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 4}
0.651443 (0.010794) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 8}
0.661191 (0.021249) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 4}
0.646549 (0.013650) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 4}
0.641631 (0.027430) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}
0.659597 (0.006709) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 4}
0.646541 (0.017426) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 4}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 8}
0.648159 (0.022999) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 4}
0.649801 (0.015929) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 4}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}
0.649817 (0.010705) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 4}
0.649809 (0.012970) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 8}
0.654703 (0.009092) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 4}
0.649801 (0.015929) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 8}
0.649793 (0.019264) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 4}
0.646549 (0.013650) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 4}
0.646533 (0.020522) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 4}
0.653061 (0.014643) with: {'batch_size': 10, 'epochs': 10, 'model__act_func': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 8}
0.672645 (0.010318) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 4}
0.685677 (0.005567) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 8}
0.697051 (0.032762) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 4}
0.679189 (0.017346) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 4}
0.716563 (0.021784) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}
0.677579 (0.023564) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 4}
0.684114 (0.032784) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 8}
0.648183 (0.012688) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 4}
0.667695 (0.033233) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 8}
0.672629 (0.010813) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 4}
0.677395 (0.056113) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 4}
0.677451 (0.043695) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}
0.664443 (0.026631) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 4}
0.677435 (0.054203) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 8}
0.651443 (0.010794) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 4}
0.651419 (0.020511) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 4}
0.666077 (0.022683) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 4}
0.648167 (0.018224) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 4}
0.667775 (0.009819) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 4}
0.649809 (0.012343) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 8, 'model__n2': 8}
0.656313 (0.018721) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 4}
0.661239 (0.002026) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.001, 'model__n1': 16, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 4}
0.705125 (0.037803) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}
0.651435 (0.013639) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 4}
0.661199 (0.020723) with: {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_Rate': 0.01, 'model__n1': 16, 'model__n2': 8}

In [51]:
pd.DataFrame(grid_result.cv_results_).sort_values(by = 'rank_test_score')

     mean_fit_time  std_fit_time  mean_score_time  std_score_time  ...  split2_test_score  mean_test_score std_test_score  rank_test_score
69       13.961266      0.598070         0.353375        0.075455  ...           0.686275         0.716563       0.021784                1
196      10.692629      0.099646         0.357602        0.061011  ...           0.632353         0.713223       0.059927                2
93       14.236423      0.759306         0.380217        0.076451  ...           0.651961         0.705125       0.037803                3
195      10.706034      0.226187         0.312838        0.024938  ...           0.691176         0.703563       0.008982                4
205      11.097187      0.246383         0.340738        0.071454  ...           0.637255         0.700223       0.045232                5
..             ...           ...              ...             ...  ...                ...              ...            ...              ...
184       4.080930      0.073755         0.406959        0.082868  ...           0.465686         0.547099       0.059231              252
17        5.221354      0.334265         0.414112        0.054082  ...           0.544118         0.526088       0.041820              253
147       4.068350      0.011022         0.353034        0.068939  ...           0.637255         0.522987       0.084846              254
153       4.141298      0.047906         0.299081        0.017618  ...           0.490196         0.508114       0.020355              255
155       4.335837      0.171595         0.356467        0.059147  ...           0.563725         0.482217       0.084457              256

[256 rows x 19 columns]

In [54]:
opt_Model = create_module(learning_Rate = 0.01,dropout_rate = 0.0,act_func = 'relu',init = 'glorot_uniform',n2 = 8,n1 = 8)
#Best of 0.716563 using {'batch_size': 10, 'epochs': 50, 'model__act_func': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_Rate': 0.01, 'model__n1': 8, 'model__n2': 8}

In [55]:
opt_Model.fit(x=X_train,
    y=y_train,
    batch_size=10,
    epochs=50,
    verbose='2')

Epoch 1/50
Epoch 2/50
Epoch 3/50
Epoch 4/50
Epoch 5/50
Epoch 6/50
Epoch 7/50
Epoch 8/50
Epoch 9/50
Epoch 10/50
Epoch 11/50
Epoch 12/50
Epoch 13/50
Epoch 14/50
Epoch 15/50
Epoch 16/50
Epoch 17/50
Epoch 18/50
Epoch 19/50
Epoch 20/50
Epoch 21/50
Epoch 22/50
Epoch 23/50
Epoch 24/50
Epoch 25/50
Epoch 26/50
Epoch 27/50
Epoch 28/50
Epoch 29/50
Epoch 30/50
Epoch 31/50
Epoch 32/50
Epoch 33/50
Epoch 34/50
Epoch 35/50
Epoch 36/50
Epoch 37/50
Epoch 38/50
Epoch 39/50
Epoch 40/50
Epoch 41/50
Epoch 42/50
Epoch 43/50
Epoch 44/50
Epoch 45/50
Epoch 46/50
Epoch 47/50
Epoch 48/50
Epoch 49/50
Epoch 50/50

In [58]:
opt_Model.get_metrics_result()

{'accuracy': 0.7394136786460876, 'loss': 0.5205807685852051}